### ISSUE TITLE
NPE when writing messages to disk where the header value is 'nulll'

### ISSUE THREAD

**Issue by AntonRoskvist** [erik-wramner/JmsTools#26]
Hi,

I just noticed that the JMSConsumer can crash with a NPE when writing messages to disk if they have header/s with a null value.

This happens at:
name.wramner.jmstools.consumer.DequeueWorker (saveMessageHeaders)
It causes the message payload to get saved but not the headers, and the message will get rolled back to the queue. The JMSConsumer crashes.

For my purposes I have solved it by adding a try/catch which works fine. I'd be happy to send a PR for it, but this raises the question of weather the message should actually get processed or not, seeing as this method essentially alters the message (removes the null headers) and saves it, instead of rolling back.

Let me know if I should send the PR or not.

Br,
Anton

**Comment by erik-wramner** [comment]
Hi Anton! Sorry for the slow feedback. A null header value seems very strange. It can hardly be portable and I can't see any valid use for it. I would propose ignoring it, but logging a warning message just in case. A PR would be appreciated.

**Comment by AntonRoskvist** [comment]
Hi,

No problem. Yeah, I don't really see any use for such headers either. These where originally sent from a client with a faulty config, so I don't really have any worries in removing them for my use case at least.

Sent a PR for the fix I mentioned before.

Br,
Anton

**Comment by erik-wramner** [comment]
Merged, thanks.
