### ISSUE TITLE
Unsupported type ActiveMQMessage

### ISSUE THREAD

**Issue by aquaplanet** [erik-wramner/JmsTools#4]
saveMessagePayload in JmsConsumer/src/main/java/name/wramner/jmstools/consumer/DequeueWorker.java does not handle plain ActiveMQMessage. This has the the unfortunate effect that one cannot download and look at Advisory topics, e.g. from the advisory ActiveMQ.Advisory.Connection.

`java -cp activemq-all-5.15.8.jar -jar consumer.jar -topic ActiveMQ.Advisory.Connection -url tcp://localhost:61616 -dir temp -user admin -pw admin`

Gives the error:
`DequeueWorker-1 WARN  name.wramner.jmstools.consumer.DequeueWorker Can't save payload for ID:localhost-36500-1554898779245-3:1:0:0:30878125, unsupported type org.apache.activemq.command.ActiveMQMessage!`

The payload files are created but empty.

**Comment by erik-wramner** [comment]
Well, it is actually not an error but just a warning. The message is saved, but as you say the payload file is empty. There is a very good reason for that: a Message has no payload. ActiveMQ uses a plain Message with all data in JMS properties for advisory messages, there is no payload. I've never seen Message used directly by another JMS provider, normally one of the sub-interfaces (BytesMessage, MapMessage, ObjectMessage, StreamMessage, TextMessage) is used, but there is nothing in the standard that prevents using Message, except then there is no way to include a payload.

I could suppress the warning, but apart from that the tool would work in the same way as it does now.
